import os
from dotenv import load_dotenv

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableSequence
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

load_dotenv()


class GradeAnswer(BaseModel):
    """Binary score to grade the answer generated by the LLM."""

    binary_score: bool = Field(
        description="Answer addresses the question, 'yes' or 'no'"
    )


llm = ChatOpenAI(api_key=os.getenv("OPENAI_API_KEY"), temperature=0)
structured_llm_grader = llm.with_structured_output(
    GradeAnswer, method="function_calling")

system = """You are a grader assessing whether an answer addresses / resolves a question. \n
    Give a binary score "yes" or "no". Yes maens that the answer addresses the question. \n"""

answer_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("human",
         "User question: \\n{question} \n\n LLM generation: \n\n{generation}"),
    ]
)

answer_grader: RunnableSequence = answer_prompt_template | structured_llm_grader
